pipeline {
    agent any
    stages {
        stage('Check ansible version') {
            steps {
                script {
                    def ansibleVersion = sh(script: 'ansible --version', returnStdout: true).trim()
                    echo "Ansible version: ${ansibleVersion}"
                }
            }
        }
    }
}
