pipeline {
    agent any
    stages {
        stage('Install Ansible') {
            steps {
                sh 'apt update && apt install -y ansible' // For Debian/Ubuntu-based systems
                // or
                // sh 'yum install -y ansible' // For RHEL/CentOS-based systems
            }
        }
        // Your other stages here
    }
}
